### PR TITLE
added activerecord to simplify crud

### PR DESCRIPTION
**Pull request by jetilton**
Your walkthrough was by far and away the best setup I have seen and even paid money for a tuorial on TestDriven.io, but your implementation blows that tutorial away.  I just didn't like how boilerplate the crud was going to be.  I turned your HeroCrud into a mixin that could be added to all the table models and reused throughout the app.  You may have done something similar, but wanted to share it since your article helped me so much.  It passes all tests, I would like to know your opinion or if you have done anything similar.

Thanks

### CODE REVIEW

**Comment by ETretyakov** [comment]
Hi @jetilton, thanks for your interest! Give me some time I'll prepare a better one. This weekend I'm going to create a separate one repository with my new setup, it will be much better)

**Comment by jetilton** [comment]
@ETretyakov, alright I am excited I will make sure to check back!

**Comment by ETretyakov** [comment]
@jetilton I haven't finished with docs and some extra examples (like Client, Redis, etc.), but the common pattern is ready -> https://github.com/ETretyakov/hero-app-v2

**Comment by jetilton** [comment]
@ETreyakov I have already taken a look and incorporated a lot of what you put up there!  Thanks for putting this together so quickly!  It really is the most well done example I have seen.  Thanks again!

**Pull request closed without merging**
